services:
  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/usr/app/data
    # Run the container processes as the provided UID:GID to avoid file ownership issues
    user: "${PUID:-1000}:${PGID:-1000}"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
