"""initial

Revision ID: 1853843a832e
Revises:
Create Date: 2025-08-26 21:32:17.847779

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1853843a832e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_archive",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("created_time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_message_archive_id"), "message_archive", ["id"], unique=False
    )
    op.drop_table("messagearchive")
    op.create_index(op.f("ix_memory_id"), "memory", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_memory_id"), table_name="memory")
    op.create_table(
        "messagearchive",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("content", sa.BLOB(), nullable=False),
        sa.Column("created_time", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("ix_message_archive_id"), table_name="message_archive")
    op.drop_table("message_archive")
    # ### end Alembic commands ###
